site_name: Advanced Configurations
edit_uri: ""
repo_url: https://github.com/quietsy/advanced-configurations
theme:
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
  name: material
  custom_dir: overrides
  favicon: images/logo.png
  logo: images/logo.png
  font:
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  homepage: https://virtualize.link
nav:
  - Home: index.md
  - Containers:
    - Awesome LSIO: awesome-lsio.md
    - Consolidating Proxies: consolidate.md
    - Optimizing Nextcloud: nextcloud.md
    - Piped: piped.md
    - Searx: searx.md
    - Securing SWAG: secure.md
    - SOCKS Proxy: socks.md
    - Split Tunnel: split.md
    - VPN Route: vpn.md
    - VPS Proxy: vps.md
  - Tools:
    - Setup Template: setup.md
    - Tmux: tmux.md